---
kind: pipeline
name: default

steps:
  - name: build
    image: golang:latest
    volumes:
      - name: deps
        path: /go
    commands:
      - apt-get -qq -y update > /dev/null && apt-get install -qq -y libasound2-dev > /dev/null
      - make

  - name: test
    image: golang:latest
    volumes:
      - name: deps
        path: /go
    commands:
      - apt-get -qq -y update > /dev/null && apt-get install -qq -y libasound2-dev > /dev/null
      - make test

  - name: linter
    image: golang:latest
    volumes:
      - name: deps
        path: /go
    commands:
      - apt-get -qq -y update > /dev/null && apt-get install -qq -y libasound2-dev > /dev/null
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
      - ./bin/golangci-lint run --timeout 5m
      - rm -r ./bin/

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      to: 790376882
      format: markdown
      token:
        from_secret: telegram_token

volumes:
  - name: deps
    host:
      path: /var/lib/cache/godeps/
