---
kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.21.5
    volumes:
      - name: deps
        path: /go
    commands:
      - apt-get -qq -y update > /dev/null && apt-get install -qq -y libasound2-dev > /dev/null
      - make

  - name: test
    image: golang:1.21.5
    volumes:
      - name: deps
        path: /go
    commands:
      - apt-get -qq -y update > /dev/null && apt-get install -qq -y libasound2-dev > /dev/null
      - make test

  - name: linter
    image: golang:1.21.5
    volumes:
      - name: deps
        path: /go
    commands:
      - apt-get -qq -y update > /dev/null && apt-get install -qq -y libasound2-dev > /dev/null
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
      - ./bin/golangci-lint run --timeout 5m
      - rm -r ./bin/

  - name: docker latest
    image: plugins/docker
    settings:
      username: depado
      password:
        from_secret: ghcr_pat
      repo: ghcr.io/depado/parakeet
      registry: ghcr.io
      tags:
        - latest
        - "${DRONE_COMMIT_SHA}"
      build_args:
        - version="latest"
        - build="${DRONE_COMMIT_SHA}"
    when:
      event: [push]
      branch: [master]

  - name: docker tag
    image: plugins/docker
    settings:
      username: depado
      password:
        from_secret: ghcr_pat
      repo: ghcr.io/depado/parakeet
      registry: ghcr.io
      tags:
        - latest
        - "${DRONE_TAG}"
        - "${DRONE_COMMIT_SHA}"
      build_args:
        - version="${DRONE_TAG}"
        - build="${DRONE_COMMIT_SHA}"
    when:
      event: [tag]

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      to: 790376882
      format: markdown
      token:
        from_secret: telegram_token

volumes:
  - name: deps
    host:
      path: /var/lib/cache/godeps/
